// Generated by CoffeeScript 1.8.0
(function() {
  var Qiita, request;

  request = require('superagent');

  Qiita = require('../kitchen/qiita');

  Qiita.setToken = function(token) {
    return Qiita._token = token;
  };

  Qiita.setEndpoint = function(endpoint) {
    return Qiita._endpoint = endpoint;
  };

  Qiita.setRequester(function(method, api, params) {
    if (typeof Promise === "undefined" || Promise === null) {
      return new Promise.reject('You should require promise or its shim');
    }
    return new Promise(function(done, reject) {
      var req, url;
      url = Qiita._endpoint + api;
      req = method === 'GET' ? request.get(url).query(params) : request[method.toLowerCase()](url).send(params);
      return req.set({
        Authorization: 'Bearer ' + Qiita._token
      }).set('Accept', 'application/json').end(function(error, res) {
        if (error) {
          return reject(error);
        }
        if (parseInt(res.statusCode, 10) >= 400) {
          error = new Error('qiita-js request error:' + method + ' ' + url + '\n' + res.body.error);
          return reject(error);
        }
        return done(res.body);
      });
    });
  });

  module.exports = Qiita;

}).call(this);
